archful = true
description = "This is package 'pycryptodome' generated automatically by pyp2spec."
summary = "Cryptographic library for Python"
version = "3.21.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "pycryptodome"
python_name = "python-pycryptodome"
url = "https://www.pycryptodome.org"
source = "%{pypi_source pycryptodome}"
archive_name = "pycryptodome"
extras = []
