archful = false
description = "This is package 'pyu2f' generated automatically by pyp2spec."
summary = "U2F host library for interacting with a U2F device over USB."
version = "0.1.5"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "pyu2f"
python_name = "python-pyu2f"
url = "https://github.com/google/pyu2f/"
source = "%{pypi_source pyu2f}"
archive_name = "pyu2f"
extras = []
