archful = false
description = "This is package 'httpcore' generated automatically by pyp2spec."
summary = "A minimal low-level HTTP client."
version = "1.0.7"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "httpcore"
python_name = "python-httpcore"
url = "https://www.encode.io/httpcore/"
source = "%{pypi_source httpcore}"
archive_name = "httpcore"
extras = [
    "asyncio",
    "http2",
    "socks",
    "trio",
]
