archful = false
description = "This is package 'durationpy' generated automatically by pyp2spec."
summary = "Module for converting between datetime.timedelta and Go's Duration strings."
version = "0.9"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "durationpy"
python_name = "python-durationpy"
url = "https://github.com/icholy/durationpy"
source = "%{pypi_source durationpy}"
archive_name = "durationpy"
extras = []
