archful = false
description = "This is package 'awx-plugins.interfaces' generated automatically by pyp2spec."
summary = "Common interfaces for implementing plugins to AWX."
version = "0.0.1~a4"
pypi_version = "0.0.1a4"
license = "gpl"
pypi_name = "awx-plugins-interfaces"
python_name = "python-awx-plugins-interfaces"
url = "https://docs.ansible.com"
source = "%{pypi_source awx_plugins_interfaces 0.0.1a4}"
archive_name = "awx_plugins_interfaces"
extras = []
