archful = false
description = "This is package 'awx-plugins-core' generated automatically by pyp2spec."
summary = "A temporary home for the essential AWX plugins"
version = "0.0.1~a9"
pypi_version = "0.0.1a9"
license = "gpl"
pypi_name = "awx-plugins-core"
python_name = "python-awx-plugins-core"
url = "https://docs.ansible.com"
source = "%{pypi_source awx_plugins_core 0.0.1a9}"
archive_name = "awx_plugins_core"
extras = [
    "credentials-aim",
    "credentials-aws-secretsmanager-credential",
    "credentials-azure-kv",
    "credentials-centrify-vault-kv",
    "credentials-conjur",
    "credentials-github-app",
    "credentials-hashivault-kv",
    "credentials-hashivault-ssh",
    "credentials-thycotic-dsv",
    "credentials-thycotic-tss",
    "inventory-azure-rm",
    "inventory-constructed",
    "inventory-controller",
    "inventory-ec2",
    "inventory-gce",
    "inventory-insights",
    "inventory-openshift-virtualization",
    "inventory-openstack",
    "inventory-rhv",
    "inventory-satellite6",
    "inventory-terraform",
    "inventory-vmware",
]
