archful = false
description = "This is package 'pycrypto' generated automatically by pyp2spec."
summary = "Cryptographic modules for Python."
version = "2.6.1"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "pycrypto"
python_name = "python-pycrypto"
url = "http://www.pycrypto.org/"
source = "%{pypi_source pycrypto}"
archive_name = "pycrypto"
extras = []
