archful = false
description = "This is package 'anyio' generated automatically by pyp2spec."
summary = "High level compatibility layer for multiple asynchronous event loop implementations"
version = "4.8.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "anyio"
python_name = "python-anyio"
url = "https://pypi.org/project/anyio/"
source = "%{pypi_source anyio}"
archive_name = "anyio"
extras = [
    "doc",
    "test",
    "trio",
]
