archful = false
description = "This is package 'pyhcl' generated automatically by pyp2spec."
summary = "HCL configuration parser for python"
version = "0.4.5"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "pyhcl"
python_name = "python-pyhcl"
url = "https://github.com/virtuald/pyhcl"
source = "%{pypi_source pyhcl}"
archive_name = "pyhcl"
extras = []
