archful = false
description = "This is package 'configobj' generated automatically by pyp2spec."
summary = "Config file reading, writing and validation."
version = "5.0.9"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "configobj"
python_name = "python-configobj"
url = "https://github.com/DiffSK/configobj"
source = "%{pypi_source configobj}"
archive_name = "configobj"
extras = []
