archful = false
description = "This is package 'h11' generated automatically by pyp2spec."
summary = "A pure-Python, bring-your-own-I/O implementation of HTTP/1.1"
version = "0.14.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "h11"
python_name = "python-h11"
url = "https://github.com/python-hyper/h11"
source = "%{pypi_source h11}"
archive_name = "h11"
extras = []
