archful = false
description = "This is package 'toml' generated automatically by pyp2spec."
summary = "Python Library for Tom's Obvious, Minimal Language"
version = "0.10.2"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "toml"
python_name = "python-toml"
url = "https://github.com/uiri/toml"
source = "%{pypi_source toml}"
archive_name = "toml"
extras = []
