archful = true
description = "This is package 'propcache' generated automatically by pyp2spec."
summary = "Accelerated property cache"
version = "0.2.1"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "propcache"
python_name = "python-propcache"
url = "https://github.com/aio-libs/propcache"
source = "%{pypi_source propcache}"
archive_name = "propcache"
extras = []
