archful = false
description = "This is package 'userpath' generated automatically by pyp2spec."
summary = "Cross-platform tool for adding locations to the user PATH"
version = "1.9.2"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "userpath"
python_name = "python-userpath"
url = "https://pypi.org/project/userpath/"
source = "%{pypi_source userpath}"
archive_name = "userpath"
extras = []
