archful = true
description = "This is package 'zstandard' generated automatically by pyp2spec."
summary = "Zstandard bindings for Python"
version = "0.23.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "zstandard"
python_name = "python-zstandard"
url = "https://github.com/indygreg/python-zstandard"
source = "%{pypi_source zstandard}"
archive_name = "zstandard"
extras = [
    "cffi",
]
