archful = false
description = "This is package 'wcwidth' generated automatically by pyp2spec."
summary = "Measures the displayed width of unicode strings in a terminal"
version = "0.2.13"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "wcwidth"
python_name = "python-wcwidth"
url = "https://github.com/jquast/wcwidth"
source = "%{pypi_source wcwidth}"
archive_name = "wcwidth"
extras = []
