archful = false
description = "This is package 'argon2-cffi' generated automatically by pyp2spec."
summary = "Argon2 for Python"
version = "23.1.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "argon2-cffi"
python_name = "python-argon2-cffi"
url = "https://pypi.org/project/argon2-cffi/"
source = "%{pypi_source argon2_cffi}"
archive_name = "argon2_cffi"
extras = [
    "dev",
    "docs",
    "tests",
    "typing",
]
