archful = false
description = "This is package 'ansi2html' generated automatically by pyp2spec."
summary = "Convert text with ANSI color codes to HTML or to LaTeX"
version = "1.9.2"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "ansi2html"
python_name = "python-ansi2html"
url = "https://pypi.org/project/ansi2html/"
source = "%{pypi_source ansi2html}"
archive_name = "ansi2html"
extras = [
    "docs",
    "test",
]
