archful = false
description = "This is package 'aiohappyeyeballs' generated automatically by pyp2spec."
summary = "Happy Eyeballs for asyncio"
version = "2.4.4"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "aiohappyeyeballs"
python_name = "python-aiohappyeyeballs"
url = "https://github.com/aio-libs/aiohappyeyeballs"
source = "%{pypi_source aiohappyeyeballs}"
archive_name = "aiohappyeyeballs"
extras = []
