archful = false
description = "This is package 'deprecated' generated automatically by pyp2spec."
summary = "Python @deprecated decorator to deprecate old python classes, functions or methods."
version = "1.2.15"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "deprecated"
python_name = "python-deprecated"
url = "https://github.com/laurent-laporte-pro/deprecated"
source = "%{pypi_source deprecated}"
archive_name = "deprecated"
extras = [
    "dev",
]
