archful = false
description = "This is package 'aws' generated automatically by pyp2spec."
summary = "Utility to manage your Amazon Web Services and run Fabric against filtered set of EC2 instances."
version = "0.2.5"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "aws"
python_name = "python-aws"
url = "https://github.com/eofs/aws"
source = "%{pypi_source aws}"
archive_name = "aws"
extras = []
