archful = true
description = "This is package 'markupsafe' generated automatically by pyp2spec."
summary = "Safely add untrusted strings to HTML/XML markup."
version = "3.0.2"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "markupsafe"
python_name = "python-markupsafe"
url = "https://pypi.org/project/MarkupSafe/"
source = "%{pypi_source markupsafe}"
archive_name = "markupsafe"
extras = []
