archful = false
description = "This is package 'prettytable' generated automatically by pyp2spec."
summary = "A simple Python library for easily displaying tabular data in a visually appealing ASCII table format"
version = "3.15.1"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "prettytable"
python_name = "python-prettytable"
url = "https://github.com/prettytable/prettytable"
source = "%{pypi_source prettytable}"
archive_name = "prettytable"
extras = [
    "tests",
]
