archful = false
description = "This is package 'masonry' generated automatically by pyp2spec."
summary = "A command line tool for composable project templating."
version = "0.1.2"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "masonry"
python_name = "python-masonry"
url = "https://github.com/MrKriss/masonry"
source = "%{pypi_source masonry}"
archive_name = "masonry"
extras = []
