archful = true
description = "This is package 'ruamel-yaml-clib' generated automatically by pyp2spec."
summary = "C version of reader, parser and emitter for ruamel.yaml derived from libyaml"
version = "0.2.12"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "ruamel-yaml-clib"
python_name = "python-ruamel-yaml-clib"
url = "https://pypi.org/project/ruamel.yaml.clib/"
source = "%{pypi_source ruamel.yaml.clib}"
archive_name = "ruamel.yaml.clib"
extras = []
