archful = false
description = "This is package 'jaraco-stream' generated automatically by pyp2spec."
summary = "routines for dealing with data streams"
version = "3.0.4"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "jaraco-stream"
python_name = "python-jaraco-stream"
url = "https://pypi.org/project/jaraco.stream/"
source = "%{pypi_source jaraco_stream}"
archive_name = "jaraco_stream"
extras = [
    "check",
    "cover",
    "doc",
    "enabler",
    "test",
    "type",
]
