archful = false
description = "This is package 'ruamel-yaml' generated automatically by pyp2spec."
summary = "ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order"
version = "0.18.10"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "ruamel-yaml"
python_name = "python-ruamel-yaml"
url = "https://pypi.org/project/ruamel.yaml/"
source = "%{pypi_source ruamel.yaml}"
archive_name = "ruamel.yaml"
extras = [
    "docs",
    "jinja2",
]
