archful = false
description = "This is package 'id' generated automatically by pyp2spec."
summary = "A tool for generating OIDC identities"
version = "1.5.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "id"
python_name = "python-id"
url = "https://pypi.org/project/id/"
source = "%{pypi_source id}"
archive_name = "id"
extras = [
    "dev",
    "lint",
    "test",
]
