archful = false
description = "This is package 'automat' generated automatically by pyp2spec."
summary = "Self-service finite-state machines for the programmer on the go."
version = "24.8.1"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "automat"
python_name = "python-automat"
url = "https://pypi.org/project/Automat/"
source = "%{pypi_source automat}"
archive_name = "automat"
extras = [
    "visualize",
]
