archful = true
description = "This is package 'grpcio-tools' generated automatically by pyp2spec."
summary = "Protobuf code generator for gRPC"
version = "1.70.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "grpcio-tools"
python_name = "python-grpcio-tools"
url = "https://grpc.io"
source = "%{pypi_source grpcio_tools}"
archive_name = "grpcio_tools"
extras = []
