archful = false
description = "This is package 'changelog-chug' generated automatically by pyp2spec."
summary = "Parser library for project Change Log documents."
version = "0.0.3"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "changelog-chug"
python_name = "python-changelog-chug"
url = "https://pypi.org/project/changelog-chug/"
source = "%{pypi_source changelog_chug}"
archive_name = "changelog_chug"
extras = [
    "build",
    "devel",
    "publish",
    "static-analysis",
    "test",
]
