archful = true
description = "This is package 'argon2-cffi-bindings' generated automatically by pyp2spec."
summary = "Low-level CFFI bindings for Argon2"
version = "21.2.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "argon2-cffi-bindings"
python_name = "python-argon2-cffi-bindings"
url = "https://github.com/hynek/argon2-cffi-bindings"
source = "%{pypi_source argon2-cffi-bindings}"
archive_name = "argon2-cffi-bindings"
extras = []
