archful = false
description = "This is package 'django-redis' generated automatically by pyp2spec."
summary = "Full featured redis cache backend for Django."
version = "5.4.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "django-redis"
python_name = "python-django-redis"
url = "https://github.com/jazzband/django-redis"
source = "%{pypi_source django-redis}"
archive_name = "django-redis"
extras = [
    "hiredis",
]
