archful = false
description = "This is package 'fabric' generated automatically by pyp2spec."
summary = "High level SSH command execution"
version = "3.2.2"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "fabric"
python_name = "python-fabric"
url = "https://fabfile.org"
source = "%{pypi_source fabric}"
archive_name = "fabric"
extras = [
    "pytest",
]
