archful = false
description = "This is package 'django-ansible-base' generated automatically by pyp2spec."
summary = "A Django app used by ansible services"
version = "2025.3.7"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "django-ansible-base"
python_name = "python-django-ansible-base"
url = "https://pypi.org/project/django-ansible-base/"
source = "%{pypi_source django_ansible_base}"
archive_name = "django_ansible_base"
extras = [
    "all",
    "api-documentation",
    "authentication",
    "channel-auth",
    "feature-flags",
    "jwt-consumer",
    "oauth2-provider",
    "redis-client",
    "resource-registry",
    "testing",
]
