archful = true
description = "This is package 'orjson' generated automatically by pyp2spec."
summary = "Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy"
version = "3.10.13"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "orjson"
python_name = "python-orjson"
url = "https://github.com/ijl/orjson"
source = "%{pypi_source orjson}"
archive_name = "orjson"
extras = []
