archful = false
description = "This is package 'httpx' generated automatically by pyp2spec."
summary = "The next generation HTTP client."
version = "0.28.1"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "httpx"
python_name = "python-httpx"
url = "https://github.com/encode/httpx"
source = "%{pypi_source httpx}"
archive_name = "httpx"
extras = [
    "brotli",
    "cli",
    "http2",
    "socks",
    "zstd",
]
