archful = false
description = "This is package 'hvac' generated automatically by pyp2spec."
summary = "HashiCorp Vault API client"
version = "2.3.0"
pypi_version = "%{version}"
license = "gpl"
pypi_name = "hvac"
python_name = "python-hvac"
url = "https://github.com/hvac/hvac"
source = "%{pypi_source hvac}"
archive_name = "hvac"
extras = [
    "parser",
]
